### PR TITLE
Inclusion request review

### PR DESCRIPTION
**Pull request by lasote**
- It is a C library, so remove libcxx (you will need to remove outdated later)
- Use of new "platforms" parameter in 1.1.1 to avoid the `cmd.replace('/p:Platform="x86"', '/p:Platform="Win32"')`
- Some pep8 fixes (not important)

### CODE REVIEW

**Review by SSE4 — APPROVED** [review]
LGTM

**Comment by lasote** [comment]
taking a look to the failed vs 15

**Comment by theirix** [comment]
Seems like replacing `cmd.replace('/p:Platform="x86"', '/p:Platform="Win32"')` with a new `platforms` parameter breaks the build. Previously all builds were x86_64 (check [the log](https://ci.appveyor.com/project/BinCrafters/conan-lcms/build/1.0.19/job/fq07eyiig0uld2aa)). Now it builds with x86 and fails.

**Comment by lasote** [comment]
Interesting, so the "platforms" uncovered a bug using the replace?

**Comment by SSE4** [comment]
not really. VS12/VS14 used Win32, but VS15 was using x86 as platform name.

**Comment by lasote** [comment]
Oh, I see. :(

**Comment by theirix** [comment]
We definitely need a comment in code

**Comment by lasote** [comment]
I still don't understand what is/was failing.

**Comment by lasote** [comment]
I pushed some changes using the `MSBuild()` helper. I was not very comfortable with the try catch to the project update. I would need to see the failures.

**Comment by lasote** [comment]
A couple of questions:
1. why using the 2013 project always?
2. ~~Is it common the replace of `MultiThreaded` with the `MT` and so on? Why is it needed? 
    Is it really needed to iterate the xml of the `vcxproj` and not doing a simple `tools.replace_in_file` ?~~ Forget about this last question, I've been investigating, I think we can/have to improve this in Conan.

**Comment by SSE4** [comment]
lcms has 2017 and 2015 projects, they can be used instead for corresponding builds
for MT, yes, it's needed to have a proper runtime
tools.replace_in_file will also do the job (however, it might replace some false positives, which I tried to avoid)

**Comment by lasote** [comment]
Take a look at the latest commit and the function `_patch_vcxproj_runtime`, I isolated that code because it should be removed soon: Thanks to this PR I got some time to investigate, I'm going to improve the MSBuild() for conan 1.2 to not require messing with the runtime (and other flags).

**Comment by theirix** [comment]
Thanks, these improvements are great! Seems like `msbuild` does not fail for successful sln upgrades as `devenv` did so it simplifies a build process.

I fixed style a little, see an attached patch: https://gist.github.com/theirix/e5635608103e6b7dad6b4bcf90cfed82

**Comment by lasote** [comment]
updated!

**Comment by theirix** [comment]
Merged to stable. All green.

**Pull request merged**
